Formatting tools and reformat code repo
kevinsadi/lei3d pull request #23
Opened 2023-08-22 15:20 UTC by keptsecret

On further inspection, saw that none of the files actually used MSVC format anyways and were all different, so used slightly modified Google format

2023-08-23 02:06 UTC, Bowers-L approved these changes

2023-08-24 01:28 UTC, kevinsadi requested changes
Video to set up clang-format on Visual Studio Code -> https://www.youtube.com/watch?v=rd8-aVc3Krg

There are two lines that seemingly do not work on my version of clang (which I thought was the newest) on Visual Studio Code. I figure it is simplest to just remove these two rules that do not work.

2023-08-24 01:28 UTC, kevinsadi commented on .clang-format
> +EmptyLineBeforeAccessModifier: LogicalBlock
remove this line 

-EmptyLineBeforeAccessModifier: LogicalBlock

2023-08-24 01:28 UTC, kevinsadi commented on .clang-format
> +SpaceBeforeCaseColon: false
remove this line 

-SpaceBeforeCaseColon: false

2023-08-24 01:44 UTC, kevinsadi approved these changes
LGTM

2023-08-24 01:45 UTC, merged