Shadows
kevinsadi/lei3d pull request #26
Opened 2023-08-31 21:44 UTC by keptsecret

It works, can be merged  
Ideally, I don't want to yet because likely need cascaded shadows and other small tweaks to camera (exposing frustum values, used later) but there aren't any conflicts so it should be fine.

2023-08-31 21:49 UTC, keptsecret commented
Seems to print "uniform does not exist" but still work just fine

2023-09-02 01:50 UTC, keptsecret commented on src/engine/rendering/Shader.cpp
> -		bind();
@kevinsadi @Bowers-L 
I removed calls to use shader program when setting uniforms, to reduce calls to the OpenGL state for overhead and to help me sift through commands when GPU debugging.
Made all relevant fixes. Pls don't put back.

2023-09-04 18:32 UTC, keptsecret commented
Changing this branch into a new features (shadows) and general fixes pr because it needs to be.

2023-09-06 02:18 UTC, Bowers-L approved these changes
I can handle camera changes in my next pr

2023-09-06 02:47 UTC, kevinsadi reviewed
Right now, I'm unable to compile this locally. It may be user error on my part though. I attempted to just checkout the repo and then regenerate the cmake and then run the lei3d project. Notably, I'm getting a `8>c1xx : fatal  error C1083: Cannot open source file: 'F:\Programming\lei3d\src\engine\main.cpp': No such file or directory`. This is on Windows 10, NVIDIA gpu. Visual Studio.

2023-09-06 02:47 UTC, kevinsadi commented on src/engine/rendering/Mesh.hpp
> +	enum RenderFlag {
What is happening here?

2023-09-06 02:47 UTC, kevinsadi commented on src/game.cpp
> +#include "core/Application.hpp"
Why is this game.cpp outside of the game folder?

2023-09-06 02:47 UTC, kevinsadi commented on src/game.cpp
> +#include "core/Application.hpp"
The same question applies to editor.cpp

2023-09-06 02:50 UTC, Bowers-L requested changes
Make sure building still works before merging.

2023-09-06 21:09 UTC, Bowers-L approved these changes

2023-09-06 22:33 UTC, merged